# Generated by Django 4.2.11 on 2024-03-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0003_alter_deviceinfo_taken_time_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.device', verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_given',
            field=models.DateField(blank=True, null=True, verbose_name='Given Date'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_taken',
            field=models.DateField(verbose_name='Device Taken Date'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.employee', verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='given_time_condition',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Given Time Condition'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='taken_time_condition',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Taken Time Condition'),
        ),
    ]
